# Site settings
title: Tanner Development Blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog/site/" # the subpath of your site, e.g. /blog/
siteurl: "/~joshuatanner/tannerdev/"
url: "" # the base hostname & protocol for your site
twitter_username: tannerdev
github_username:  tannerdev

# Build settings
markdown: kramdown
