#Build With jekyll build -d ../site --watch
# Site settings
title: Tanner Development Blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  TannerDevelopment is passionate about computer science, web development
  and maps!  We are super greatful for all of the great tutorials and blog
  posts other have created.  We want to help give back by posting our 
  experiences and tutorials on new technologies.
baseurl: "/blog/site/" # the subpath of your site, e.g. /blog/
siteurl: "/~joshuatanner/tannerdev/"
url: "" # the base hostname & protocol for your site
twitter_username: tannerdev
github_username:  tannerdev

# Build settings
markdown: kramdown
